### PR TITLE
Attempt to use the db and still close it

### PR DESCRIPTION
**Pull request by flub**
This is an alternative to see if this helps with the fd leakage.

### CODE REVIEW

**Comment by ff2000** [comment]
I gave it a go.
1) before this patch I immediately got >200 open fds.
```
lrwx------ 1 franz franz 64 Sep  1 13:05 2 -> /dev/pts/3
lr-x------ 1 franz franz 64 Sep  1 13:05 20 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 200 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 201 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 202 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 203 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 204 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 205 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 206 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 207 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 208 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 209 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 21 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 210 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 211 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 212 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 213 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 214 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 215 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 216 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 217 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 218 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 219 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 22 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 220 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 221 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 222 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 23 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 24 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 25 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 26 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 27 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 28 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 29 -> /home/franz/.mail/.notmuch/xapian/position.glass
lrwx------ 1 franz franz 64 Sep  1 13:05 3 -> 'anon_inode:[eventpoll]'
lr-x------ 1 franz franz 64 Sep  1 13:05 30 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 31 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 32 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 33 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 34 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 35 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 36 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 37 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 38 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:05 39 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lrwx------ 1 franz franz 64 Sep  1 13:05 4 -> 'socket:[2381770]'
```
2) after this patch open fds stayed at 20 with just 4 being the xapian files:
```
lrwx------ 1 franz franz 64 Sep  1 13:20 0 -> /dev/pts/3
lrwx------ 1 franz franz 64 Sep  1 13:19 1 -> /dev/pts/3
lr-x------ 1 franz franz 64 Sep  1 13:20 10 -> 'pipe:[2447742]'
lrwx------ 1 franz franz 64 Sep  1 13:20 11 -> /dev/dri/renderD128
l-wx------ 1 franz franz 64 Sep  1 13:20 12 -> 'pipe:[2447742]'
lr-x------ 1 franz franz 64 Sep  1 13:20 13 -> 'pipe:[2447743]'
l-wx------ 1 franz franz 64 Sep  1 13:20 14 -> 'pipe:[2447743]'
lr-x------ 1 franz franz 64 Sep  1 13:20 15 -> /home/franz/.mail/.notmuch/xapian/docdata.glass
lr-x------ 1 franz franz 64 Sep  1 13:20 16 -> /home/franz/.mail/.notmuch/xapian/termlist.glass
lr-x------ 1 franz franz 64 Sep  1 13:20 17 -> /home/franz/.mail/.notmuch/xapian/position.glass
lr-x------ 1 franz franz 64 Sep  1 13:20 18 -> /home/franz/.mail/.notmuch/xapian/postlist.glass
lrwx------ 1 franz franz 64 Sep  1 13:20 2 -> /dev/pts/3
lrwx------ 1 franz franz 64 Sep  1 13:20 3 -> 'anon_inode:[eventpoll]'
lrwx------ 1 franz franz 64 Sep  1 13:20 4 -> 'socket:[2447739]'
lrwx------ 1 franz franz 64 Sep  1 13:20 5 -> 'socket:[2447740]'
lr-x------ 1 franz franz 64 Sep  1 13:20 6 -> 'pipe:[2447741]'
l-wx------ 1 franz franz 64 Sep  1 13:20 7 -> 'pipe:[2447741]'
l-wx------ 1 franz franz 64 Sep  1 13:20 8 -> /dev/null
lrwx------ 1 franz franz 64 Sep  1 13:20 9 -> /dev/dri/renderD128
```

Even more important: I didn't see any issues with this patch, everything worked as before.
So it seems we have a fix! Thx @flub !

**Comment by flub** [comment]
Nice!  Thanks for trying it out.

I still don't understand why it seems none of this was eventually being cleaned up without this patch.  I thought it would.  Or perhaps "eventual" is just too slow at the rate alot uses this.

**Comment by pazz** [comment]
Sorry to rush but what's the status on this one? It's blocking our move to notmuch2 over at [alot](https://github.com/pazz/alot/issues/1539) somewhat.. Cheers!

**Comment by flub** [comment]
I don't thing anything is still blocked on me here, but correct me if I'm wrong.

**Comment by pazz** [comment]
well then this should get pushed to notmuch master so that we (alot) can go on and merge our PRs :)

**Comment by ff2000** [comment]
I also would vote for merging to pazz/alot, probably not directly to master so that some more testing can be done.
Also tests are currently broken because of `Could not find a version that satisfies the requirement notmuch2>=0.30` (from the Travis output on https://github.com/pazz/alot/pull/1511)

**Comment by pazz** [comment]
@ff2000 Apologies, I was confused! AlI this while I though this was a PR to notmuch! 

Why don't we simply add this patch to [#1511](https://github.com/pazz/alot/pull/1511),
fix travis and merge this into alot master, which is a testing branch after all?

It looks like the travis build is messed up again:
We install notmuch and bindings manually, and this seems to have worked. 
https://travis-ci.com/github/pazz/alot/jobs/357333548#L717
I don't see why pip still looks for notmuch2 >=0.30 online.
(The whole travis setup is really messed up: it intalls stuff from all over the place, including ubuntu mainline, PPAs, github, and pypi. time to clean this up or better yet, move to github actions).

**Comment by flub** [comment]
this has been incorporated upstream i think and no longer needed (trimming my open PR list ;) )

**Pull request closed without merging**
